% This script will create the a mat file that has the borders of each state
%
% Written By: Stephen Forczyk
% Created: Oct 29,2021
% Revised: -----
% Classification: Unclassified
global numcounties S2;
global StateFIPSFile numstatesinlist numvalidstates StateBoundaryFileList;
global numstateentries;
global StateBoundaryData;

global fid;
global widd2 lend2;
global initialtimestr igrid ijpeg ilog imovie;
global vert1 hor1 widd lend;
global vert2 hor2 machine;
global chart_time;
global Fz1 Fz2;
global idirector mov izoom iwindow;

global matpath GOES16path;
global jpegpath tiffpath;
global smhrpath excelpath ascpath;
global ipowerpoint PowerPointFile scaling stretching padding;
global ichartnum;
global ColorList RGBVals ColorList2 xkcdVals LandColors;
global orange bubblegum brown brightblue;
% additional paths needed for mapping
global matpath1 mappath matlabpath USshapefilepath dtedpath;
global moviepath firepath;
global stateboundarypath;
global jpegpath northamericalakespath logpath pdfpath govjpegpath;
global GOES16Band1path GOES16Band2path GOES16Band3path GOES16Band4path;
global GOES16Band5path GOES16Band6path GOES16Band7path GOES16Band8path
global GOES16Band9path GOES16Band10path GOES16Band11path GOES16Band12path;
global GOES16Band13path GOES16Band14path GOES16Band15path GOES16Band16path;
global GOES16CloudTopHeightpath GOES16CloudTopTemppath GOES16Lightningpath;
global GOES16ConusBand1path shapefilepath Countryshapepath figpath;
global mappath gridpath countyshapepath nationalshapepath NationalCountiesShp
global DayMonthNonLeapYear DayMonthLeapYear CalendarFileName;
global baseimagepath selectedImageFolder;
global hurricanepath geotiffpath;
global pwd;

stateboundarypath='D:\Forczyk\Map_Data\USStateBoundaryFinalFiles\';
nationalshapepath='D:\Forczyk\Map_Data\NationalShapeFiles\';
NationalCountiesShp='cb_2018_us_county_500k.shp';
matpath1='D:\Forczyk\Map_Data\MAT_Files_Geographic\';
StateFIPSFile='StateFipCodeDataRev1.mat';
StateBoundaryFileList=cell(1,6);
StateBoundaryFileList{1,1}='FileName';
StateBoundaryFileList{1,2}='StateName';
StateBoundaryFileList{1,3}='PostalCode';
StateBoundaryFileList{1,4}='StateFIPSCode';
StateBoundaryFileList{1,5}='LatVariableName';
StateBoundaryFileList{1,6}='LonVariableName';
StateBoundaryFileList{2,1}='Alabama_Boundaries.mat';
StateBoundaryFileList{2,2}='Alabama';
StateBoundaryFileList{2,3}='AL';
StateBoundaryFileList{2,4}=1;
StateBoundaryFileList{2,5}='AlabamaLat';
StateBoundaryFileList{2,6}='AlabamaLon';
StateBoundaryFileList{3,1}='Alaska_Boundaries.mat';
StateBoundaryFileList{3,2}='Alaska';
StateBoundaryFileList{3,3}='AK';
StateBoundaryFileList{3,4}=2;
StateBoundaryFileList{3,5}='AlaskaLat';
StateBoundaryFileList{3,6}='AlaskaLon';
StateBoundaryFileList{4,1}='Arizona_Boundaries.mat';
StateBoundaryFileList{4,2}='Arizona';
StateBoundaryFileList{4,3}='AZ';
StateBoundaryFileList{4,4}=4;
StateBoundaryFileList{4,5}='ArizonaLat';
StateBoundaryFileList{4,6}='ArizonaLon';
StateBoundaryFileList{5,1}='Arkansas_Boundaries.mat';
StateBoundaryFileList{5,2}='Arkansas';
StateBoundaryFileList{5,3}='AR';
StateBoundaryFileList{5,4}=5;
StateBoundaryFileList{5,5}='ArkansasLat';
StateBoundaryFileList{5,6}='ArkansasLon';
StateBoundaryFileList{6,1}='California_Boundaries.mat';
StateBoundaryFileList{6,2}='California';
StateBoundaryFileList{6,3}='CA';
StateBoundaryFileList{6,4}=6;
StateBoundaryFileList{6,5}='CaliforniaLat';
StateBoundaryFileList{6,6}='CaliforniaLon';
StateBoundaryFileList{7,1}='Colorado_Boundaries.mat';
StateBoundaryFileList{7,2}='Colorado';
StateBoundaryFileList{7,3}='CO';
StateBoundaryFileList{7,4}=8;
StateBoundaryFileList{7,5}='ColoradoLat';
StateBoundaryFileList{7,6}='ColoradoLon';
StateBoundaryFileList{8,1}='Connecticut_Boundaries.mat';
StateBoundaryFileList{8,2}='Connecticut';
StateBoundaryFileList{8,3}='CT';
StateBoundaryFileList{8,4}=9;
StateBoundaryFileList{8,5}='ConnLat';
StateBoundaryFileList{8,6}='ConnLon';
StateBoundaryFileList{9,1}='Delaware_Boundaries.mat';
StateBoundaryFileList{9,2}='Delaware';
StateBoundaryFileList{9,3}='DE';
StateBoundaryFileList{9,4}=10;
StateBoundaryFileList{9,5}='DelawareLat';
StateBoundaryFileList{9,6}='DelawareLon';
StateBoundaryFileList{10,1}='Florida_Boundaries.mat';
StateBoundaryFileList{10,2}='Florida';
StateBoundaryFileList{10,3}='FL';
StateBoundaryFileList{10,4}=12;
StateBoundaryFileList{10,5}='FloridaLat';
StateBoundaryFileList{10,6}='FloridaLon';
StateBoundaryFileList{11,1}='Georgia_Boundaries.mat';
StateBoundaryFileList{11,2}='Georgia';
StateBoundaryFileList{11,3}='GA';
StateBoundaryFileList{11,4}=13;
StateBoundaryFileList{11,5}='GeorgiaLat';
StateBoundaryFileList{11,6}='GeorgiaLon';
StateBoundaryFileList{12,1}='Hawaii_Boundaries.mat';
StateBoundaryFileList{12,2}='Hawaii';
StateBoundaryFileList{12,3}='HI';
StateBoundaryFileList{12,4}=15;
StateBoundaryFileList{12,5}='HawaiiLat';
StateBoundaryFileList{12,6}='HawaiiLon';
StateBoundaryFileList{13,1}='Idaho_Boundaries.mat';
StateBoundaryFileList{13,2}='Idaho';
StateBoundaryFileList{13,3}='ID';
StateBoundaryFileList{13,4}=16;
StateBoundaryFileList{13,5}='IdahoLat';
StateBoundaryFileList{13,6}='IdahoLon';
StateBoundaryFileList{14,1}='Illinois_Boundaries.mat';
StateBoundaryFileList{14,2}='Illinois';
StateBoundaryFileList{14,3}='IL';
StateBoundaryFileList{14,4}=17;
StateBoundaryFileList{14,5}='IllinoisLat';
StateBoundaryFileList{14,6}='IllinoisLon';
StateBoundaryFileList{15,1}='Indiana_Boundaries.mat';
StateBoundaryFileList{15,2}='Indiana';
StateBoundaryFileList{15,3}='IN';
StateBoundaryFileList{15,4}=18;
StateBoundaryFileList{15,5}='IndianaLat';
StateBoundaryFileList{15,6}='IndianaLon';
StateBoundaryFileList{16,1}='Iowa_Boundaries.mat';
StateBoundaryFileList{16,2}='Iowa';
StateBoundaryFileList{16,3}='IA';
StateBoundaryFileList{16,4}=19;
StateBoundaryFileList{16,5}='IowaLat';
StateBoundaryFileList{16,6}='IowaLon';
StateBoundaryFileList{17,1}='Kansas_Boundaries.mat';
StateBoundaryFileList{17,2}='Kansas';
StateBoundaryFileList{17,3}='KS';
StateBoundaryFileList{17,4}=20;
StateBoundaryFileList{17,5}='KansasLat';
StateBoundaryFileList{17,6}='KansasLon';
StateBoundaryFileList{18,1}='Kentucky_Boundaries.mat';
StateBoundaryFileList{18,2}='Kentucky';
StateBoundaryFileList{18,3}='KY';
StateBoundaryFileList{18,4}=21;
StateBoundaryFileList{18,5}='KentuckyLat';
StateBoundaryFileList{18,6}='KentuckyLon';
StateBoundaryFileList{19,1}='Louisiana_Boundaries.mat';
StateBoundaryFileList{19,2}='Louisiana';
StateBoundaryFileList{19,3}='LA';
StateBoundaryFileList{19,4}=22;
StateBoundaryFileList{19,5}='LouisianaLat';
StateBoundaryFileList{19,6}='LouisianaLon';
StateBoundaryFileList{20,1}='Maine_Boundaries.mat';
StateBoundaryFileList{20,2}='Maine';
StateBoundaryFileList{20,3}='ME';
StateBoundaryFileList{20,4}=23;
StateBoundaryFileList{20,5}='MaineLat';
StateBoundaryFileList{20,6}='MaineLon';
StateBoundaryFileList{21,1}='Maryland_Boundaries.mat';
StateBoundaryFileList{21,2}='Maryland';
StateBoundaryFileList{21,3}='MD';
StateBoundaryFileList{21,4}=24;
StateBoundaryFileList{21,5}='MarylandLat';
StateBoundaryFileList{21,6}='MarylandLon';
StateBoundaryFileList{22,1}='Massachusetts_Boundaries.mat';
StateBoundaryFileList{22,2}='Massachusetts';
StateBoundaryFileList{22,3}='MA';
StateBoundaryFileList{22,4}=25;
StateBoundaryFileList{22,5}='MassLat';
StateBoundaryFileList{22,6}='MassLon';
StateBoundaryFileList{23,1}='Michigan_Boundaries.mat';
StateBoundaryFileList{23,2}='Michigan';
StateBoundaryFileList{23,3}='MI';
StateBoundaryFileList{23,4}=26;
StateBoundaryFileList{23,5}='MichiganLat';
StateBoundaryFileList{23,6}='MichiganLon';
StateBoundaryFileList{24,1}='Minnesota_Boundaries.mat';
StateBoundaryFileList{24,2}='Minnesota';
StateBoundaryFileList{24,3}='MN';
StateBoundaryFileList{24,4}=27;
StateBoundaryFileList{24,5}='MinnesotaLat';
StateBoundaryFileList{24,6}='MinnesotaLon';
StateBoundaryFileList{25,1}='Mississippi_Boundaries.mat';
StateBoundaryFileList{25,2}='Mississippi';
StateBoundaryFileList{25,3}='MS';
StateBoundaryFileList{25,4}=28;
StateBoundaryFileList{25,5}='MississippiLat';
StateBoundaryFileList{25,6}='MississippiLon';
StateBoundaryFileList{26,1}='Missouri_Boundaries.mat';
StateBoundaryFileList{26,2}='Missouri';
StateBoundaryFileList{26,3}='MO';
StateBoundaryFileList{26,4}=29;
StateBoundaryFileList{26,5}='MissouriLat';
StateBoundaryFileList{26,6}='MissouriLon';
StateBoundaryFileList{27,1}='Montana_Boundaries.mat';
StateBoundaryFileList{27,2}='Montana';
StateBoundaryFileList{27,3}='MT';
StateBoundaryFileList{27,4}=30;
StateBoundaryFileList{27,5}='MontanaLat';
StateBoundaryFileList{27,6}='MontanaLon';
StateBoundaryFileList{28,1}='Nebraska_Boundaries.mat';
StateBoundaryFileList{28,2}='Nebraska';
StateBoundaryFileList{28,3}='NE';
StateBoundaryFileList{28,4}=31;
StateBoundaryFileList{28,5}='NebraskaLat';
StateBoundaryFileList{28,6}='NebraskaLon';
StateBoundaryFileList{29,1}='Nevada_Boundaries.mat';
StateBoundaryFileList{29,2}='Nevada';
StateBoundaryFileList{29,3}='NV';
StateBoundaryFileList{29,4}=32;
StateBoundaryFileList{29,5}='NevadaLat';
StateBoundaryFileList{29,6}='NevadaLon';
StateBoundaryFileList{30,1}='NewHampshire_Boundaries.mat';
StateBoundaryFileList{30,2}='New_Hampshire';
StateBoundaryFileList{30,3}='NH';
StateBoundaryFileList{30,4}=33;
StateBoundaryFileList{30,5}='NHLat';
StateBoundaryFileList{30,6}='NHLon';
StateBoundaryFileList{31,1}='NewJersey_Boundaries.mat';
StateBoundaryFileList{31,2}='New_Jersey';
StateBoundaryFileList{31,3}='NJ';
StateBoundaryFileList{31,4}=34;
StateBoundaryFileList{31,5}='NewJerseyLat';
StateBoundaryFileList{31,6}='NewJerseyLon';
StateBoundaryFileList{32,1}='NewMexico_Boundaries.mat';
StateBoundaryFileList{32,2}='New_Mexico';
StateBoundaryFileList{32,3}='NM';
StateBoundaryFileList{32,4}=35;
StateBoundaryFileList{32,5}='NewMexicoLat';
StateBoundaryFileList{32,6}='NewMexicoLon';
StateBoundaryFileList{33,1}='NewYork_Boundaries.mat';
StateBoundaryFileList{33,2}='New_York';
StateBoundaryFileList{33,3}='NY';
StateBoundaryFileList{33,4}=36;
StateBoundaryFileList{33,5}='NewYorkLat';
StateBoundaryFileList{33,6}='NewYorkLon';
StateBoundaryFileList{34,1}='NorthCarolina_Boundaries.mat';
StateBoundaryFileList{34,2}='North_Carolina';
StateBoundaryFileList{34,3}='NC';
StateBoundaryFileList{34,4}=37;
StateBoundaryFileList{34,5}='NorthCarolinaLat';
StateBoundaryFileList{34,6}='NorthCarolinaLon';
StateBoundaryFileList{35,1}='NorthDakota_Boundaries.mat';
StateBoundaryFileList{35,2}='North_Dakota';
StateBoundaryFileList{35,3}='ND';
StateBoundaryFileList{35,4}=38;
StateBoundaryFileList{35,5}='NorthDakotaLat';
StateBoundaryFileList{35,6}='NorthDakotaLon';
StateBoundaryFileList{36,1}='Ohio_Boundaries.mat';
StateBoundaryFileList{36,2}='Ohio';
StateBoundaryFileList{36,3}='OH';
StateBoundaryFileList{36,4}=39;
StateBoundaryFileList{36,5}='OhioLat';
StateBoundaryFileList{36,6}='OhioLon';
StateBoundaryFileList{37,1}='Oklahoma_Boundaries.mat';
StateBoundaryFileList{37,2}='Oklahoma';
StateBoundaryFileList{37,3}='OK';
StateBoundaryFileList{37,4}=40;
StateBoundaryFileList{37,5}='OklahomaLat';
StateBoundaryFileList{37,6}='OklahomaLon';
StateBoundaryFileList{38,1}='Oregon_Boundaries.mat';
StateBoundaryFileList{38,2}='Oregon';
StateBoundaryFileList{38,3}='OR';
StateBoundaryFileList{38,4}=41;
StateBoundaryFileList{38,5}='OregonLat';
StateBoundaryFileList{38,6}='OregonLon';
StateBoundaryFileList{39,1}='Pennsylvania_Boundaries.mat';
StateBoundaryFileList{39,2}='Pennsylvania';
StateBoundaryFileList{39,3}='PA';
StateBoundaryFileList{39,4}=42;
StateBoundaryFileList{39,5}='PennLat';
StateBoundaryFileList{39,6}='PennLon';
StateBoundaryFileList{40,1}='RhodeIsland_Boundaries.mat';
StateBoundaryFileList{40,2}='Rhode_Island';
StateBoundaryFileList{40,3}='RI';
StateBoundaryFileList{40,4}=44;
StateBoundaryFileList{40,5}='RhodeIslandLat';
StateBoundaryFileList{40,6}='RhodeIslandLon';
StateBoundaryFileList{41,1}='SouthCarolina_Boundaries.mat';
StateBoundaryFileList{41,2}='South_Carolina';
StateBoundaryFileList{41,3}='SC';
StateBoundaryFileList{41,4}=45;
StateBoundaryFileList{41,5}='SouthCarolinaLat';
StateBoundaryFileList{41,6}='SouthCarolinaLon';
StateBoundaryFileList{42,1}='SouthDakota_Boundaries.mat';
StateBoundaryFileList{42,2}='South_Dakota';
StateBoundaryFileList{42,3}='SD';
StateBoundaryFileList{42,4}=46;
StateBoundaryFileList{42,5}='SouthDakotaLat';
StateBoundaryFileList{42,6}='SouthDakotaLon';
StateBoundaryFileList{43,1}='Tennessee_Boundaries.mat';
StateBoundaryFileList{43,2}='Tennessee';
StateBoundaryFileList{43,3}='TN';
StateBoundaryFileList{43,4}=47;
StateBoundaryFileList{43,5}='TennesseeLat';
StateBoundaryFileList{43,6}='TennesseeLon';
StateBoundaryFileList{44,1}='Texas_Boundaries.mat';
StateBoundaryFileList{44,2}='Texas';
StateBoundaryFileList{44,3}='TX';
StateBoundaryFileList{44,4}=48;
StateBoundaryFileList{44,5}='TexasLat';
StateBoundaryFileList{44,6}='TexasLon';
StateBoundaryFileList{45,1}='Utah_Boundaries.mat';
StateBoundaryFileList{45,2}='Utah';
StateBoundaryFileList{45,3}='UT';
StateBoundaryFileList{45,4}=49;
StateBoundaryFileList{45,5}='UtahLat';
StateBoundaryFileList{45,6}='UtahLon';
StateBoundaryFileList{46,1}='Vermont_Boundaries.mat';
StateBoundaryFileList{46,2}='Vermont';
StateBoundaryFileList{46,3}='VT';
StateBoundaryFileList{46,4}=50;
StateBoundaryFileList{46,5}='VermontLat';
StateBoundaryFileList{46,6}='VermontLon';
StateBoundaryFileList{47,1}='Virginia_Boundaries.mat';
StateBoundaryFileList{47,2}='Virgina';
StateBoundaryFileList{47,3}='VA';
StateBoundaryFileList{47,4}=51;
StateBoundaryFileList{47,5}='VirginiaLat';
StateBoundaryFileList{47,6}='VirginiaLon';
StateBoundaryFileList{48,1}='Washington_Boundaries.mat';
StateBoundaryFileList{48,2}='Washington';
StateBoundaryFileList{48,3}='WA';
StateBoundaryFileList{48,4}=53;
StateBoundaryFileList{48,5}='WashingtonLat';
StateBoundaryFileList{48,6}='WashingtonLon';
StateBoundaryFileList{49,1}='WestVirginia_Boundaries.mat';
StateBoundaryFileList{49,2}='West_Virginia';
StateBoundaryFileList{49,3}='WV';
StateBoundaryFileList{49,4}=54;
StateBoundaryFileList{49,5}='WestVirginiaLat';
StateBoundaryFileList{49,6}='WestVirginiaLon';
StateBoundaryFileList{50,1}='Wisconsin_Boundaries.mat';
StateBoundaryFileList{50,2}='Wisconsin';
StateBoundaryFileList{50,3}='WI';
StateBoundaryFileList{50,4}=55;
StateBoundaryFileList{50,5}='WisconsinLat';
StateBoundaryFileList{50,6}='WisconsinLon';
StateBoundaryFileList{51,1}='Wyoming_Boundaries.mat';
StateBoundaryFileList{51,2}='Wyoming';
StateBoundaryFileList{51,3}='WY';
StateBoundaryFileList{51,4}=56;
StateBoundaryFileList{51,5}='WyomingLat';
StateBoundaryFileList{51,6}='WyomingLon';
[rows,cols]=size(StateBoundaryFileList);
numstateentries=rows-1;
StateBoundaryData=cell(51,1);
StateBoundaryData{1,1}='StateName';
StateBoundaryData{1,2}='PostalCode';
StateBoundaryData{1,3}='StateFIPSCode';
StateBoundaryData{1,4}='BoundaryLats';
StateBoundaryData{1,5}='BoundaryLons';
StateBoundaryData{1,6}='NumberOfCounties';
StateBoundaryData{1,7}='Included FIPS Codes';
StateBoundaryData{1,8}='Included Entry #';
StateBoundaryData{1,9}='Included County Names';
%% Call some routines that will create nice plot window sizes and locations
% Establish selected run parameters
imachine=2;
if(imachine==1)
    widd=720;
    lend=580;
    widd2=1000;
    lend2=700;
elseif(imachine==2)
    widd=1080;
    lend=812;
    widd2=1000;
    lend2=700;
elseif(imachine==3)
    widd=1296;
    lend=974;
    widd2=1200;
    lend2=840;
end
% Set a specific color order
set(0,'DefaultAxesColorOrder',[1 0 0;
    1 1 0;0 1 0;0 0 1;0.75 0.50 0.25;
    0.5 0.75 0.25; 0.25 1 0.25;0 .50 .75]);
% Set up some defaults for a PowerPoint presentationwhos
scaling='true';
stretching='false';
padding=[75 75 75 75];
igrid=1;
% Set up paramters for graphs that will center them on the screen
[hor1,vert1,Fz1,Fz2,machine]=SetScreenCoordinates(widd,lend);
[hor2,vert2,Fz1,Fz2,machine]=SetScreenCoordinates(widd2,lend2);
chart_time=5;
idirector=1;
initialtimestr=datestr(now);
% Start by reading in the National County Boundaries Data
eval(['cd ' nationalshapepath(1:length(nationalshapepath)-1)]);
shapefilename=NationalCountiesShp;
S2=shaperead(shapefilename,'UseGeoCoords',true);
numcounties=length(S2);
% Continue by loading in the StateFipsCode data
eval(['cd ' matpath1(1:length(matpath1)-1)]);
load(StateFIPSFile);
numstatesinlist=length(StateFIPSFile);
numvalidstates=50;
% now go through the list of state file names to load the needed data for
% each state
eval(['cd ' stateboundarypath(1:length(stateboundarypath)-1)]);
for n=1:numstateentries
    nowFile=StateBoundaryFileList{1+n,1};
    nowState=StateBoundaryFileList{1+n,2};
    nowPostalCode=StateBoundaryFileList{1+n,3};
    nowFIPSCode=StateBoundaryFileList{1+n,4};
    load(nowFile);
    BoundaryLats=eval(StateBoundaryFileList{1+n,5});
    BoundaryLons=eval(StateBoundaryFileList{1+n,6});
    StateBoundaryData{1+n,1}=nowState;
    StateBoundaryData{1+n,2}=nowPostalCode;
    StateBoundaryData{1+n,3}=nowFIPSCode;
    StateBoundaryData{1+n,4}=BoundaryLats;
    StateBoundaryData{1+n,5}=BoundaryLons;
    StateBoundaryData{1+n,6}=0;
% Now find out how many counties fall in this state
    icounties=0;
    for m=1:numcounties
        retStateFIPS=str2double(S2(m).STATEFP);
        if(retStateFIPS==nowFIPSCode)
            icounties=icounties+1;
        end
    end
% Now repeat the process get the county fips codes and entry numbers
    StateBoundaryData{1+n,6}=icounties;
    IncludedCountyFIPSCodes=zeros(icounties,1);
    IncludedCountyEntryNumbers=zeros(icounties,1);
    IncludedCountyNames=cell(icounties,1);
    icounties=0;
    for m=1:numcounties
        retStateFIPS=str2double(S2(m).STATEFP);
        retCountyFIPS=str2double(S2(m).COUNTYFP);
        retCountyNAME=char(S2(m).NAME);
        if(retStateFIPS==nowFIPSCode)
            icounties=icounties+1;
            IncludedCountyFIPSCodes(icounties,1)=retCountyFIPS;
            IncludedCountyEntryNumbers(icounties,1)=m;
            IncludedCountyNames{icounties,1}=retCountyNAME;
        end
    end
    StateBoundaryData{1+n,7}=IncludedCountyFIPSCodes;
    StateBoundaryData{1+n,8}=IncludedCountyEntryNumbers;
    StateBoundaryData{1+n,9}=IncludedCountyNames;
end
% Now save this file
save('All_USCounties_BoundaryData.mat','StateBoundaryData');


